name: Build and Deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: release

    - name: Install dependencies
      run: yarn install

    - name: Build production javascipt
      run: yarn build
    
    - name: SSH deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        
    - name: Set up and restart production server
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: |
          export NODE_ENV=production
          export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          export SPINCORD_DISCOGS_KEY=${{ secrets.SPINCORD_DISCOGS_KEY }}
          export SPINCORD_DISCOGS_SECRET=${{ secrets.SPINCORD_DISCOGS_SECRET }}
          cd spincord
          yarn install
          pm2 kill && pm2 start dist/app.js
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        # passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        SPINCORD_DISCOGS_KEY: ${{ secrets.SPINCORD_DISCOGS_KEY }}
        SPINCORD_DISCOGS_SECRET: ${{ secrets.SPINCORD_DISCOGS_SECRET }}


    - name: update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
