name: Spincord CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      # - name: Run unit tests
      #   run: yarn test

      - name: Build
        run: yarn build

  deploy:
    steps:
      - uses: actions/checkout@v2

      - name: Push to server
        run: echo 'this will eventually just deploy to like heroku or something'
