name: Post release to Jekyll Blog

on:
  release:
    types: [published]

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'

      - name: Create blog post
        run: |
          echo $GITHUB_REF
          read release_name release_date release_url release_body < <(echo $(curl -s -H "Accept: application/vnd.github.v3+json" 'https://api.github.com/repos/kmrn/spincord/releases/latest' | jq -r '.tag_name, .published_at, .url, .body'))
          cat << EOF > ./_posts/$(date +%F)-release-$release_name.markdown
          ---
          layout: post
          title: Release $release_name
          date: $release_date
          author: spincord-ci
          categories: release
          ---

          $release_body

          [View this release on GitHub]($release_url)
          
          EOF

      - name: Add and commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          author_name: Spincord
          author_email: spincord@kamranpayne.com
          message: 'post release info to blog'
          ref: 'gh-pages'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
